### ISSUE TITLE
Theme demo broken on Hugo Themes showcase

### ISSUE THREAD

**Issue by onedrawingperday** [niklasbuschmann/contrast-hugo#3]
Hello @niklasbuschmann 

I am one of the maintainers of [Hugo Themes](https://themes.gohugo.io/) and I noticed that your latest updates broke the theme demo.

The console shows the following errors:

```
Failed to get JSON resource "themes/contrast-hugo/static/font-awesome/icons.json": unexpected end of JSON input
```
```
hugoThemes/contrast-hugo/layouts/_default/baseof.html:32:18": execute of template failed: template: _default/single.html:32:18: executing "_default/single.html" at <index $font_awesome .Identifier>: error calling index: index of untyped nil

```

I noticed that in [lines 29-32](https://github.com/niklasbuschmann/contrast-hugo/blob/master/layouts/_default/baseof.html#L29-L32) of `layouts/_default/baseof.html` you invoke a menu configuration.

However you do not provide an exampleSite directory and Hugo cannot find the relevant menu.

It seems that you need to provide this directory and also make sure to configure the menu in the config of the exampleSite.

Once you do the above please let me know.

**Comment by niklasbuschmann** [comment]
My bad - this should be fixed now

**Comment by onedrawingperday** [comment]
No the theme is not fixed.

You need to [configure a Hugo menu](https://gohugo.io/content-management/menus/#add-non-content-entries-to-a-menu) before [calling it](https://github.com/niklasbuschmann/contrast-hugo/blob/master/layouts/_default/baseof.html#L29-L32) in the templates.

As I said above you need to provide an exampleSite with the menu configuration.

**Comment by niklasbuschmann** [comment]
The theme is tested against the hugoBasicExample and works with the menu provided by it, so I doubt it is necessary to provide an exampleSite. (Sorry if I'm misunderstanding something here)

**Comment by onedrawingperday** [comment]
There is no svg icon .Identifier in the HugoBasicExample config.

When I test your theme locally with the hugoBasicExample it fails on its own, as well as with the [Hugo Themes Build Script](https://github.com/gohugoio/hugoThemes/blob/master/README.md#testing-a-theme-with-the-hugo-themes-website-build-script) because what you have defined [here](https://github.com/niklasbuschmann/contrast-hugo/blob/master/layouts/_default/baseof.html#L30) cannot be found, hence the nil pointer.

You **have to** create an exampleSite directory and provide a config with the menu configuration that you mention in [lines 28-35](https://github.com/niklasbuschmann/contrast-hugo/blame/master/README.md#L28-L35) of the README.

I don’t know how you are able to render a site with the theme in its current state.

**Comment by niklasbuschmann** [comment]
I added an if clause to ensure that the icon actually exists, so I hope this fixes the issue. Unfortunately I can't verify this as somehow I'm unable to reproduce the issue, although I agree that Hugo should have failed there.

**Comment by onedrawingperday** [comment]
I confirm the fix.

The theme was updated in https://github.com/gohugoio/hugoThemes/commit/ab385b747e9d2fd7e44d11f74da4eb2095d281ea and its demo will be fixed shortly once deployment of the Hugo Themes Showcase is finished.
